language: rust
rust:
- nightly
- beta
- stable
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
before_deploy:
- cargo doc --verbose
- cargo package --verbose
deploy:
  provider: releases
  api_key:
    secure: GjugkoRWPpkA5U+fDtPIXVN7mz5vd1uI+o/9i/8er/a0yEPxzq1DqKZhQ+X/qjiYZqZpq14TprezQhsI3yIDoBO8ktZF3qUffM0ceV74kIUhjV4t9U/lWkNAVwve3Z7dNOgpAIpRWfGXkpwGEb/8tkr+ugg0yz9oB9m/FHQ6FO7AqHWv8JLvh/riyaQ2hWc4Rzh8/5j9DIE53jJZEVGA4RjJFXDIegsWtp/o+P+LhFYoCHOumcSgzesgyPT/6y2ud4UdogIitsPBk6Q0vfwCRguVLF+6gDTGJUPO94cO20x8PIR+lhPEeCWPbAH7mL7E/Y1MfUTrX45lnkvxeZDlbjrb9xC1TiyKBsFZvENS1QpNhpQNcozs9PctDcyPyGA2pPsEvAmH7Sb8F8NFH67boTRG8JB2STBt465kJJPr5IBBVelrMttX+uy00LngQHjLuA929IPpeAqhcCxJ2grM8t5VBsp0l5cgrPgWNLCG6++kiRyFuSRRnRWEJ2a/fo0kLAOf6xrHO6nS7LqLF6dfC27NG148tE8HZiGugTuenMz0UulAL9pYsrqHbm5CiycH6Uk0xhWIdnP6Pt3DchXebeR1xjLtWRYNqY9QrEgFibVtd/suiVoW8wk/omAZZ6yyNuwBUhJx66OIEUb80TWznJTUO3F48GBtCC0P8r2foMo=
  file: target/package/slack_api-${TRAVIS_TAG:1}.crate
  skip_cleanup: true
  on:
    repo: slack-rs/slack-rs-api
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable
after_deploy:
- cargo publish --token "$CRATES_IO_TOKEN"
- |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=slack/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: G5B20TuKlUg3OuSZn639H/ZhhsCkel2qyfu2e3ifJUflQZwiqwkYQTWP38JcoEU9tpfS4Mt+zxqPRYpL+zE6G/Pf7IpE3BWelYRCuX1Y7P6NAWq8YvOh7YKI/MhRhYaAYTxfRwZfPRQfB+4dzB3/2YINXcW5mrHihIQuI6nigRjfsM7KB+1N3WKzuz6QDyAYtiZvViSeN/BJrk4kDcWMnoLXp6K2iZ7Q8Lswc3fHFM6JE7Ku1nB31glrc7BimYnemIGVsYQ2mA0Vwi3vDRB2ORZUPPtPtV+tEsHxsfEHM5p1fwF6qO1ZfvdyauyOfQ2gnzdGNSGNEpMbK+T4jkqBaeQL6sM2nmtd3QA62WuCW0KA66iLA+7Y/3SpM3KmsyL7DAsvNjokG9zLaekEIeqp4hnIKwh2mQfjhH1Wd9+XzG25t4uhnz8HJsiKkWv9iF8qv91Fcv6qdiUGSAAhD731UYezxjMGqsoNHOdtRcoa9yDdHooniApURY/7l3p6fn0qC3SkniJYwau9+O0hYU+cdqV+DzB+R+eo2DpoU/pWxyxQoPwWbEzHUVf+5oP+UQ3L/TbLqcRGfwVn9ynQ32AFukBQHhgdQF7T6USc0t8TYCPfD9PY+P7mf/8EuNf7GHGsvw80ZUyuW8aiG9VbnqzOBQD0kX58svfdyE+NBJi7Fy4=
  - secure: gL35BFVkuCOvxq+SIfQHAQfWV90AW6mFmUmw2WN6H+36S0jeWoyU935ZmkYpo5eT+bUWNgH4bqvShOS7bY8J1vTlpLhePyHptTV40jnFOg1J73Vb8fQXUhNQJRtofVp2yqxr0RhVAL8+GRgo5PU3iZ44bN9qBExNSg7KAqdlw4ppSb7cWDqELx1qn04EGOOuXhv45xRC0K3Wk/8bkbopRZTLvQgODWdldmvVZZbcfqY0jtI3tCjGUVgXnhb2YCELO6+HwYstIc+m9eoZtOye1D4IJpG2VwAa79HtEWVGVFzyLyMb8SArHpkYK/rwbTrcLF3alIuQ0tNg5egfFtWntoUZprjBWncd/eR3wxdaZwcBHVScza9QwMuBWAgHEyiWjDxL7YTczvlxl9DDioEZXmrmnM8EmMC7GoIvw+x1pAD1A9bnELQTFwUZG9D0ZrcWe4D6huvwt585mZtronGlc1j+sjlB5qmdGH4fLwnA4iDQsiXEuzjAJCw4Y1sQ1fTOXbu9b/92tfN39RobcnCI0gZuYkq7b0BBjY/hyk9puKYawIvckdVDK/rzSdwVTiFL/uTpC+cdChHs++Zn5apbKPOiT/WBxoEvVIx3X+cy1zDKNxDOqPGE4J2S2WANc2Y7IXGdvxtGZx0YPsF1RS3ARSZQBZZSmpZlghIu3ZaodZE=
