[package]
name = "slack_api"
version = "0.14.0"
authors = ["Benjamin Elder <ben.the.elder@gmail.com>", "Matt Jones <mthjones@gmail.com>"]
repository = "https://github.com/slack-rs/slack-rs-api.git"
documentation = "http://slack-rs.github.io/slack-rs-api/slack_api/"
description = "Interface for the Slack Web API"
license = "Apache-2.0"

[dependencies]
hyper = "0.9.4"
rustc-serialize = "0.3.18"

[dev-dependencies]
yup-hyper-mock = "1.3.2"
